### ISSUE TITLE
Improve the news system.

### ISSUE THREAD

**Issue by alexnita3** [alexnita3/GalaxyRP#67]
**Suggestion:**
Improve the news system so that everything is stored in the database, and people can add/remove news in any channels they wish.

**Reason for suggestion:**
The current system is quite limiting, and people don't really end up using it very much because of it.

**How do you see it working?**
Have a new table in the database for news, where the news ID, news channel and news text will be stored. 
`/news add <channel> <text>` Will add a new entry provided the correct permissions are assigned.
Since the channel is an argument, it can be used to define the different channels.
`/news <channel>` should run a query to grab all the news articles that belong in that channel. (A simple SQL query should do the trick)
If there are no results, "No news present in this channel, or the channel does not exist." should be displayed.

**Comment by TriForceX** [comment]
i have two ideas to make it better:
1. make a global server news to show constrantly in a certain amount of time
2. make an entity model to show the news by category (interactive)
  - player press the +use button on it and it shows the category
  - player must say the category on chat and press +use button again to see it

**Comment by alexnita3** [comment]
Done! (No news entity as asking around revealed there wasn't much demand for it)
