### ISSUE TITLE
Add client version check

### ISSUE THREAD

**Issue by TriForceX** [alexnita3/GalaxyRP#74]
The mod should have a client version check to let the server admins and players be warned if a player is not running the same version as the server, this is usually intended to let the players get the latest version of the mod (or the same as the one used by the server) so they can prevent issues, bugs, and other things caused by a different code, it can be useful too if a player has a mod newer than the server, so they can warn the server admins that theres a new version.

i would suggest a cvar for that, like `g_clientRequired` where:
0 = Disable
1 = Alert players without the mod or different mod version (Just a warning on client begin)
2 = Same as option 1 but it force (and keep them) into spectator mode

**Comment by alexnita3** [comment]
I like this, a small suggestion for if the car is set to 2.

A client print should be displayed to the user perhaps, saying something along the lines of:

"You have been forced into spectator mode because your client isn't up to date. Please update from galaxyrp.uk"

**Comment by TriForceX** [comment]
> 
> 
> I like this, a small suggestion for if the car is set to 2.
> 
> A client print should be displayed to the user perhaps, saying something along the lines of:
> 
> "You have been forced into spectator mode because your client isn't up to date. Please update from galaxyrp.uk"

yes of course, we can change the text, but is intented to be a center-print message.
in my mod looks like this if you dont have the client:
![imagen](https://user-images.githubusercontent.com/16083854/133703635-5c1b1377-d90b-4e9b-8b9c-bea8ade789a4.png)

if you have an different client looks like this:
![imagen](https://user-images.githubusercontent.com/16083854/133703756-1cefc23b-0a6a-41fc-a107-1720b9ec5c62.png)

**Comment by alexnita3** [comment]
Yup, exactly that

**Comment by TriForceX** [comment]
this is done and working
![image](https://user-images.githubusercontent.com/16083854/157340241-b1fc34d7-32ef-42bc-af0e-e46db3c1bcec.png)
