### ISSUE TITLE
Force clientside cache reload

### ISSUE THREAD

**Issue by TriForceX** [alexnita3/GalaxyRP#79]
JKA has an small issue regarding some assets cache load, due its saved once fs_game (mod) gets loaded it doesnt reload at all if the player moves to another fs_game.

For example if the player is on a JA+ server and moves to a GalaxyRP server the main clientside stuff will be loaded, except splash screen, fonts and animation files. Ive asked about this on JKcommunity and theres no way to solve that without a hard work on the engine side. so the only way to get a full cache reload is doing a /vid_restart but that require to do it manually on console...

Note: This doesnt happen if the player load the fs_game (mod) before join/start the server, so is an issue only if the player came from another server or access a server having the default fs_game instead the mod one.

To handle this i would like to add something on clientside to detect if the player has a different fs_game so it will trigger a /vid_restart command only in the first join.

**Comment by alexnita3** [comment]
Sounds good!

**Comment by TriForceX** [comment]
Fixed on commit 6a2566f
